# -*- mode: ruby -*-
# vi: set ft=ruby :

# Please don't change it unless you know what you're doing.
VAGRANTFILE_API_VERSION = "2"

SUPPLY_DIR = "provisioning"

$server_box = "centos/7"
$server_vm_cpus = 1
# bare centos utilize ~570 MB (lol, no)
# $server_vm_memory = 1024

PROJECT = "edu"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = $server_box

  $service = "nginx-reverse-proxy"
  $name = "#{PROJECT}--#{$service}"
  config.vm.define $name do |subconfig|
    subconfig.vm.hostname = $name
    # DO NOT USE static IP ending in ".1", because is very often used by the router
    # and can cause the network to not work properly.
    subconfig.vm.network :private_network, ip: "10.0.0.2"
    subconfig.vm.provision "shell", path: "#{SUPPLY_DIR}/centos7x86_64-nginx.sh"

    subconfig.vm.provider "virtualbox" do |virtualbox|
      virtualbox.cpus = $server_vm_cpus
      virtualbox.memory = 256
    end
  end


  $service = "direct-chats"
  NODES = 2
  (0...NODES).each do |i|
    $name = "#{PROJECT}--#{$service}-#{i}"
    config.vm.define $name do |subconfig|
      subconfig.vm.hostname = $name
      # DO NOT USE static IP ending in ".1", because is very often used by the router
      # and can cause the network to not work properly.
      subconfig.vm.network :private_network, ip: "10.1.0.#{i + 2}"
      subconfig.vm.provision "shell", path: "#{SUPPLY_DIR}/centos7x86_64-nodejs.sh"
      subconfig.vm.provision "shell", path: "#{SUPPLY_DIR}/git-direct-chats.sh"

      subconfig.vm.provider "virtualbox" do |virtualbox|
        virtualbox.cpus = $server_vm_cpus
        virtualbox.memory = 384
      end
    end

    $name = "#{PROJECT}--#{$service}-db-#{i}"
    config.vm.define $name do |subconfig|
      subconfig.vm.hostname = $name
      # DO NOT USE static IP ending in ".1", because is very often used by the router
      # and can cause the network to not work properly.
      subconfig.vm.network :private_network, ip: "10.2.0.#{i + 2}"
      # subconfig.vm.network :forwarded_port, guest: 5432, host: 15432
      subconfig.vm.provision "shell", path: "#{SUPPLY_DIR}/centos7x86_64-postgres.sh"
      subconfig.vm.provision "shell", path: "#{SUPPLY_DIR}/postgres-direct-chats.sh"

      subconfig.vm.provider "virtualbox" do |virtualbox|
        virtualbox.cpus = $server_vm_cpus
        virtualbox.memory = 512
      end
    end
  end

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

end
